import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "@/store/auth";

export const metadata = {
  title: {
    default:"next final project || TechFlow",
    template:"%s || TechFlow"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  <html>
      <body className="min-h-full flex flex-col">   
         <AuthProvider>

        <Navbar/>
   
        {children}
        <Toaster position="top-right" />
        <Footer/>
        </AuthProvider>
        </body>
        </html>

  );
}
